name: summer_project_2025
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - anyio=4.10.0=py311haa95532_0
  - aom=3.6.0=hd77b12b_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - arrow-cpp=21.0.0=h0399227_0
  - asttokens=3.0.0=py311haa95532_0
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - beautifulsoup4=4.12.3=pyha770c72_1
  - black=25.9.0=py311haa95532_0
  - blas=1.0=mkl
  - blinker=1.9.0=py311haa95532_0
  - bokeh=3.8.0=py311haa95532_0
  - bottleneck=1.4.2=py311h57dcf0c_0
  - brotli-python=1.2.0=py311hd3493e3_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.11.4=haa95532_0
  - cairo=1.16.0=h85cdd14_6
  - certifi=2025.11.12=py311haa95532_0
  - cffi=1.17.1=py311he736701_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=py311haa95532_0
  - cloudpickle=3.1.1=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.1=py311haa95532_0
  - cpuonly=2.0=0
  - cryptography=45.0.5=py311h5e0b3ae_0
  - dash=1.19.0=pyhd3eb1b0_0
  - dash-core-components=1.3.1=py_0
  - dash-html-components=1.0.1=py_0
  - dash-renderer=1.1.2=py_0
  - dash-table=4.4.1=pyhd3eb1b0_0
  - dask=2025.10.0=py311haa95532_0
  - dask-core=2025.10.0=py311haa95532_2
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.11=py311h5da7b33_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - distributed=2025.10.0=py311haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h8ddb27b_0
  - filelock=3.17.0=py311haa95532_0
  - flask=3.1.2=py311haa95532_0
  - flask-compress=1.17=py311haa95532_0
  - fontconfig=2.14.1=hb33846d_3
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - frozendict=2.4.6=py311he736701_0
  - future=1.0.0=py311haa95532_0
  - gflags=2.2.2=hd77b12b_1
  - glog=0.5.0=hd77b12b_1
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py311h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - greenlet=3.2.4=py311h885b0b7_0
  - h11=0.16.0=py311haa95532_1
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=10.2.0=he2f9f60_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - html5lib=1.1=pyhd8ed1ab_2
  - httpcore=1.0.9=py311haa95532_0
  - httpx=0.28.1=py311haa95532_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py311haa95532_1
  - ipython=9.1.0=py311haa95532_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - itsdangerous=2.2.0=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - jinja2=3.1.6=py311haa95532_0
  - joblib=1.4.2=py311haa95532_0
  - jpeg=9e=h827c3e9_3
  - jsonpatch=1.33=py311haa95532_1
  - jsonpointer=3.0.0=py311haa95532_0
  - jupyter_client=8.6.3=py311haa95532_0
  - jupyter_core=5.8.1=py311haa95532_0
  - kiwisolver=1.4.8=py311h5da7b33_0
  - krb5=1.21.3=he4457a5_1
  - langchain=0.3.27=py311haa95532_0
  - langchain-core=0.3.77=py311haa95532_0
  - langchain-text-splitters=0.3.11=py311haa95532_0
  - langgraph=1.0.1=py311haa95532_1
  - langgraph-checkpoint=3.0.0=py311hbc747e5_0
  - langgraph-prebuilt=1.0.1=py311haa95532_1
  - langgraph-sdk=0.2.9=py311haa95532_1
  - langsmith=0.4.32=py311haa95532_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libavif=1.1.1=h827c3e9_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.16.0=h97e0424_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.2=h405b238_0
  - libgrpc=1.71.0=hf4237ab_0
  - libiconv=1.18=h135ad9c_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_1
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=ha2884a9_4
  - libtiff=4.7.0=h404307b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - libxslt=1.1.43=h25c3957_0
  - locket=1.0.0=py311haa95532_0
  - lxml=5.3.0=py311h395c83e_1
  - lz4=4.4.5=py311hb1efef3_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib-base=3.10.0=py311he19b0ae_0
  - matplotlib-inline=0.1.6=py311haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - msgpack-python=1.1.1=py311h5da7b33_0
  - multitasking=0.0.12=pyhd8ed1ab_0
  - mypy_extensions=1.0.0=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - networkx=3.4.2=py311haa95532_0
  - numexpr=2.11.0=py311hdb065b2_0
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.5.4=h725018a_0
  - orc=2.2.0=hf43e1a1_0
  - ormsgpack=1.11.0=py311h114bc41_0
  - packaging=24.2=py311haa95532_0
  - pandas=2.3.1=py311h885b0b7_0
  - parso=0.8.4=py311haa95532_0
  - partd=1.4.2=py311haa95532_0
  - pathspec=0.12.1=py311haa95532_1
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.3.0=py311hb328d1f_0
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h2bbff1b_1
  - platformdirs=4.3.7=py311haa95532_0
  - prompt-toolkit=3.0.43=py311haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h827c3e9_1
  - psycopg2=2.9.10=py311h827c3e9_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=21.0.0=py311ha5e6156_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=py311haa95532_0
  - pypdf2=3.0.1=py311haa95532_0
  - pyqt=6.7.1=py311h378bd72_2
  - pyqt6-sip=13.9.1=py311h02ab6af_2
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.13=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-lmdb=1.6.2=py311h5da7b33_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py311h827c3e9_0
  - python_abi=3.11=2_cp311
  - pytokens=0.2.0=py311haa95532_0
  - pytorch=2.5.1=py3.11_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=py311haa95532_0
  - pywin32=308=py311h5da7b33_0
  - pyyaml=6.0.2=py311h827c3e9_0
  - pyzmq=26.2.0=py311h5da7b33_0
  - qtbase=6.7.3=hd088775_3
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebsockets=6.7.3=h885b0b7_1
  - re2=2024.07.02=h214f63a_0
  - requests=2.32.4=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=py311haa95532_0
  - scikit-learn=1.6.1=py311h585ebfc_0
  - scipy=1.15.3=py311h180bac5_0
  - seaborn=0.13.2=py311haa95532_3
  - setuptools=78.1.1=py311haa95532_0
  - sip=6.10.0=py311h5da7b33_0
  - six=1.17.0=py311haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sniffio=1.3.0=py311haa95532_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.7=pyhd8ed1ab_0
  - sqlalchemy=2.0.43=py311hda9a48d_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - tblib=3.1.0=py311haa95532_0
  - tenacity=9.1.2=py311haa95532_0
  - threadpoolctl=3.5.0=py311h746a85d_0
  - tk=8.6.14=h5e9d12e_1
  - toolz=1.0.0=py311haa95532_0
  - tornado=6.5.1=py311h827c3e9_0
  - tqdm=4.67.1=py311h746a85d_0
  - traitlets=5.14.3=py311haa95532_0
  - typing-extensions=4.15.0=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=15.1.0=py311h827c3e9_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py311haa95532_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - werkzeug=3.1.3=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xxhash=0.8.0=h2bbff1b_3
  - xyzservices=2025.4.0=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yfinance=0.2.28=pyhd8ed1ab_0
  - zeromq=4.3.5=hd77b12b_0
  - zict=3.0.0=py311haa95532_0
  - zipp=3.21.0=py311haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zstandard=0.23.0=py311he736701_2
  - zstd=1.5.6=h8880b57_0
  - pip:
    - absl-py==2.3.1
    - aioitertools==0.12.0
    - annotated-types==0.7.0
    - astunparse==1.6.3
    - attrs==25.3.0
    - bcrypt==4.3.0
    - bibtexparser==1.4.3
    - blis==1.3.0
    - boto3==1.39.7
    - botocore==1.39.7
    - catalogue==2.0.10
    - catboost==1.2.8
    - clarabel==0.11.1
    - cloudpathlib==0.21.1
    - confection==0.1.5
    - contourpy==1.3.2
    - cvxpy==1.7.0
    - cycler==0.12.1
    - cymem==2.0.11
    - dnspython==2.7.0
    - einops==0.8.1
    - emmet-core==0.84.9rc0
    - flatbuffers==25.2.10
    - fonttools==4.59.0
    - fsspec==2025.7.0
    - gast==0.6.0
    - google-pasta==0.2.0
    - grpcio==1.73.1
    - h5py==3.14.0
    - iniconfig==2.1.0
    - jmespath==1.0.1
    - jsonlines==4.0.0
    - jsonschema==4.24.1
    - jsonschema-specifications==2025.4.1
    - keras==3.10.0
    - langcodes==3.5.0
    - language-data==1.3.0
    - latexcodec==3.0.1
    - libclang==18.1.1
    - lightgbm==4.6.0
    - maggma==0.71.5
    - marisa-trie==1.2.1
    - markdown==3.8.2
    - markdown-it-py==3.0.0
    - matminer==0.9.3
    - matplotlib==3.10.3
    - mdurl==0.1.2
    - ml-dtypes==0.5.1
    - mongomock==4.3.0
    - monty==2025.3.3
    - mp-api==0.45.7
    - murmurhash==1.0.13
    - namex==0.1.0
    - narwhals==1.47.1
    - nltk==3.9.1
    - numpy==2.1.3
    - opencv-python==4.12.0.88
    - opt-einsum==3.4.0
    - optree==0.16.0
    - orjson==3.11.0
    - osqp==1.0.4
    - palettable==3.3.3
    - paramiko==3.5.1
    - patsy==1.0.1
    - plotly==6.2.0
    - pluggy==1.6.0
    - preshed==3.0.10
    - protobuf==5.29.5
    - psycopg2-binary==2.9.11
    - pybtex==0.25.1
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - pydantic-settings==2.10.1
    - pydash==8.0.5
    - pymatgen==2025.6.14
    - pymongo==4.10.1
    - pynacl==1.5.0
    - pyparsing==3.2.3
    - pytest==8.4.1
    - python-dotenv==1.1.1
    - python-graphviz==0.21
    - referencing==0.36.2
    - regex==2024.11.6
    - rich==14.0.0
    - rpds-py==0.26.0
    - ruamel-yaml==0.18.14
    - ruamel-yaml-clib==0.2.12
    - s3transfer==0.13.0
    - scs==3.2.7.post2
    - sentinels==1.0.0
    - shellingham==1.5.4
    - smart-open==7.3.0.post1
    - spacy==3.8.7
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - spglib==2.6.0
    - srsly==2.5.1
    - sshtunnel==0.4.0
    - statsmodels==0.14.5
    - sympy==1.13.1
    - tabulate==0.9.0
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - tensorflow==2.19.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==3.1.0
    - thinc==8.3.6
    - typer==0.16.0
    - typing-inspection==0.4.1
    - uncertainties==3.2.3
    - wasabi==1.1.3
    - weasel==0.4.1
    - wrapt==1.17.2
    - xgboost==3.0.2
prefix: D:\conda_envs\summer_project_2025
